name: MGMobEscape
main: com.comze_instancelabs.mgmobescape.Main
version: 1.3.5
author: instancelabs
softdepend: [Vault, MinigamesAPI]
depend: [MinigamesAPI]
loadbefore: [MinigamesAPI]
commands:
   dragonescape:
      description: Main command
      usage: /dragonescape <action>
      aliases: [de]
   escapethemob:
      description: Main command
      usage: /escapethemob <action>
      aliases: [etm]
