name: MGMobEscape
main: com.comze_instancelabs.mgmobescape.Main
version: ${minigames.releaseversion}-${minigames.timestamp}
author: [instancelabs, TheMrQuake, mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   dragonescape:
      description: Main command
      usage: /dragonescape <action>
      aliases: [de]
   escapethemob:
      description: Main command
      usage: /escapethemob <action>
      aliases: [etm]
